prototipos:
  - identificador: landing-institucional
    nome: "Landing institucional"
    file_key: "LANDING-PASSO2-202405"
    link_visualizacao: "https://www.figma.com/file/LANDING-PASSO2-202405/landing-institucional"
    responsavel: "Patrícia Andrade"
    revisores:
      - "Equipe Design Alpha"
      - "Equipe Engenharia Beta"
    ultima_atualizacao: "2024-05-27"
    escopo:
      - "Hero responsivo"
      - "Seção de depoimentos"
      - "Grade de produtos"
    notas_validacao:
      - "Componentes base sincronizados com tokens tema-padrao v1.1."
      - "Protótipo validado pela Squad Marketing em 2024-05-27."
    configuracao_api:
      token_servico: "svc-parser-figma"
      permissao: "leitura"
      verificado_em: "2024-05-27"
    observacoes: "Inclui variações mobile, notas de intenção para parser e anchors de layout."
  - identificador: fluxo-formulario
    nome: "Fluxo de conversão com formulário"
    file_key: "FORM-PASSO2-202405"
    link_visualizacao: "https://www.figma.com/file/FORM-PASSO2-202405/fluxo-formulario"
    responsavel: "Leonardo Mota"
    revisores:
      - "Equipe Design Alpha"
      - "Equipe Produto Gama"
    ultima_atualizacao: "2024-05-27"
    escopo:
      - "Formulário com validações"
      - "Página de confirmação"
      - "Estados de erro"
    notas_validacao:
      - "Campos conectados a tokens tema-padrao v1.1 e máscaras aprovadas."
      - "Fluxo revisado em 2024-05-27 com foco em acessibilidade."
    configuracao_api:
      token_servico: "svc-parser-figma"
      permissao: "leitura"
      verificado_em: "2024-05-27"
    observacoes: "Comentários descrevem mensagens dinâmicas e origens de dados fictícias."
  - identificador: componentes-dinamicos
    nome: "Biblioteca de componentes dinâmicos"
    file_key: "DINAMICO-PASSO2-202405"
    link_visualizacao: "https://www.figma.com/file/DINAMICO-PASSO2-202405/componentes-dinamicos"
    responsavel: "Sofia Lima"
    revisores:
      - "Equipe Engenharia Beta"
      - "Equipe QA Delta"
    ultima_atualizacao: "2024-05-27"
    escopo:
      - "Carrossel automatizado"
      - "Acordião com variantes"
      - "Cartões interativos"
    notas_validacao:
      - "Estados complexos conferidos com tokens tema-padrao v1.1."
      - "Interações e animações confirmadas pelo time de design em 2024-05-27."
    configuracao_api:
      token_servico: "svc-parser-figma"
      permissao: "leitura"
      verificado_em: "2024-05-27"
    observacoes: "Mapeamento de interações com descrições anexas para automação."
